"""Phase 5 comparison and qualification infrastructure."""

from .anchors import (
    ABSOLUTE_HORIZON_FLOAT_TOLERANCE_DEGREES,
    ABSOLUTE_HORIZON_POLICY_VERSION,
    ANCHOR_GEOMETRY_VERSION,
    ANCHOR_QUALIFICATION_VERSION,
    ANCHOR_REGISTRY_VERSION,
    BOOK_SUPPORT_TYPE_ORDER,
    BOOK_SUPPORT_TYPES,
    NATIVE_FIRST_CANDIDATE_POLICY_VERSION,
    NATIVE_CANDIDATE_POLICY_VERSION,
    SUPPORT_POLICY_VERSION,
    VISUAL_FALLBACK_ACTION_LIMIT,
    VISUAL_FALLBACK_POLICY_VERSION,
    build_geometry_candidate_plan,
    build_native_first_candidate_plan,
    normalize_absolute_horizon_degrees,
    build_type_balanced_native_candidate_plan,
    build_target_independent_coverage_route,
    build_target_independent_visual_fallback_route,
    public_anchor_reference,
)
from .interventions import EvaluatorIntervention
from .protocol import (
    PHASE5_METRIC_SCHEMA_VERSION,
    PHASE5_PROTOCOL_VERSION,
    PHASE5_REQUIRED_METRICS,
    QualificationRecord,
    build_formal_manifest,
    select_first_passing,
    validate_formal_manifest,
)
from .search import (
    SEARCH_ROUTE_SCHEMA_VERSION,
    FrozenSearchRoute,
    FrozenSearchRouteState,
    SearchRouteError,
    load_frozen_search_route,
)
from .r2_stability import (
    REQUIRED_PRECONDITIONS as R2_STABILITY_REQUIRED_PRECONDITIONS,
    STABILITY_POLICY_VERSION,
    STABILITY_TRIALS_PER_POSE,
    StabilityQueryError,
    audit_start_pose_stability,
)
from .target_lock import (
    TARGET_LOCK_APPROACH_ACTION_BUDGET,
    TARGET_LOCK_POLICY_VERSION,
    TARGET_LOCK_RECOVERY_ACTION_BUDGET,
    SharedTargetLockPolicy,
)

__all__ = [
    "ABSOLUTE_HORIZON_FLOAT_TOLERANCE_DEGREES",
    "ABSOLUTE_HORIZON_POLICY_VERSION",
    "ANCHOR_GEOMETRY_VERSION",
    "ANCHOR_QUALIFICATION_VERSION",
    "ANCHOR_REGISTRY_VERSION",
    "BOOK_SUPPORT_TYPE_ORDER",
    "BOOK_SUPPORT_TYPES",
    "NATIVE_FIRST_CANDIDATE_POLICY_VERSION",
    "NATIVE_CANDIDATE_POLICY_VERSION",
    "EvaluatorIntervention",
    "PHASE5_METRIC_SCHEMA_VERSION",
    "PHASE5_PROTOCOL_VERSION",
    "PHASE5_REQUIRED_METRICS",
    "QualificationRecord",
    "SEARCH_ROUTE_SCHEMA_VERSION",
    "FrozenSearchRoute",
    "FrozenSearchRouteState",
    "SearchRouteError",
    "R2_STABILITY_REQUIRED_PRECONDITIONS",
    "STABILITY_POLICY_VERSION",
    "STABILITY_TRIALS_PER_POSE",
    "StabilityQueryError",
    "SharedTargetLockPolicy",
    "TARGET_LOCK_APPROACH_ACTION_BUDGET",
    "TARGET_LOCK_POLICY_VERSION",
    "TARGET_LOCK_RECOVERY_ACTION_BUDGET",
    "SUPPORT_POLICY_VERSION",
    "VISUAL_FALLBACK_ACTION_LIMIT",
    "VISUAL_FALLBACK_POLICY_VERSION",
    "build_geometry_candidate_plan",
    "build_native_first_candidate_plan",
    "normalize_absolute_horizon_degrees",
    "build_type_balanced_native_candidate_plan",
    "build_target_independent_coverage_route",
    "build_target_independent_visual_fallback_route",
    "audit_start_pose_stability",
    "build_formal_manifest",
    "public_anchor_reference",
    "load_frozen_search_route",
    "select_first_passing",
    "validate_formal_manifest",
]
